### ISSUE TITLE
Change name to something more explicit

### ISSUE THREAD

**Issue by pydanny** [earle/django-bootstrap#28] opened 2012-02-05 16:52 UTC
Just a suggestion but django-bootstrap could mean:
- A bootstrap Django project
- A set of templates for Twitter bootstrap
- A form library for twitter bootstrap :)

Perhaps something like django-bootstrap-forms?

**Comment by jterrace** [comment] 2012-04-09 14:19
I think this can be closed as duplicate of #38

**Comment by pthrasher** [comment] 2012-04-13 16:29
Closing as duplicate. Let's move the discussion over to the above referenced issue.

**Closed as completed by pthrasher** 2012-04-13 16:29 UTC
